apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hetzner-spc
  namespace: kube-system
spec:
  provider: azure
  parameters:
    clientID: "<AZURE_CLIENT_ID>"
    keyvaultName: "<KEYVAULT_NAME>"
    tenantId: "$<AZURE_TENANT_ID>"

    objects: |
      array:
        - |
          objectName: "<keyvault-secret-name>"
          objectType: secret

  secretObjects:
  - secretName: hetzner-csi-secret
    type: Opaque
    data:
      - objectName: "<keyvault-secret-name>"
        key: hcloudToken
